const GET_USER = "user:GET_USER";
const UPDATE_PROFILE = "user:UPDATE_PROFILE";
const SOFT_DELETE_USER = "user:SOFT_DELETE_USER";
const DELETE_USER = "user:DELETE_USER";
const GET_ALL_USERS = "user:GET_ALL_USERS";


module.exports = {
    GET_ALL_USERS, GET_USER, UPDATE_PROFILE, SOFT_DELETE_USER, DELETE_USER
}