const { GET_USER, GET_ALL_USERS, DELETE_USER, SOFT_DELETE_USER, UPDATE_PROFILE, RESERT_PASSWORD } = require("../../modules/users/endPoint");

module.exports = [GET_USER, GET_ALL_USERS, DELETE_USER, SOFT_DELETE_USER, UPDATE_PROFILE, RESERT_PASSWORD]